Polished up README
pyoncord/BunnyManager pull request #8
Opened 2024-05-24 18:13 UTC by Jalenzzz

Added special thanks and polished up README

2024-07-10 21:39 UTC, Ushie requested changes

2024-07-10 21:39 UTC, Ushie commented on README.md
> +* [@Xinto](https://github.com/X1nto/) - For the preference manager.
I would include Wing for the overall maintenance of the upstream repository

2024-07-10 21:39 UTC, Ushie commented on README.md
> +###### This application is not affiliated with or endorsed by Discord Inc. Use of modified versions of the Discord app may violate Discord’s terms of service. Use at your own risk.
This can be moved to the header and utilize [GitHub-flavored MD to show a warning](https://github.com/orgs/community/discussions/16925)

2024-07-10 21:39 UTC, Ushie commented on README.md
> +BunnyManager is a user-friendly application for Android that allows you to download and manage modified versions of the Discord app. Enhance your Discord experience with custom features and tweaks th
I believe this section is unnecessary, as the About section of the repository fulfils it

2024-07-25 15:47 UTC, wakearray commented on README.md
> +BunnyManager is a user-friendly application for Android that allows you to download and manage modified versions of the Discord app. Enhance your Discord experience with custom features and tweaks th
That About section says:
> Install Bunny on an Android device with ease!

Unless the About section shows differently for me than for others, no where does it explain *what* Bunny is. As bunnies are one of the most commonly found animals in the US, if I search `bunny` or `bunny android` on GitHub, nothing related to Discord shows up in the first page of results (Not even Google knows what I'm asking for). 

I found this repo through https://apps.obtainium.imranr.dev/ and this pull request is the only reason I now know what this repo is, so I'd like to voice an opinion in favor of keeping this part or at least some form of description suggesting this repo relates to Discord modding.

2024-07-25 15:50 UTC, Rico040 commented
most useful pr

2024-07-25 16:58 UTC, Jalenzzz commented on README.md
> +BunnyManager is a user-friendly application for Android that allows you to download and manage modified versions of the Discord app. Enhance your Discord experience with custom features and tweaks th
I feel the repository didn't have an informative About Me hence why I had added it. The main [repo's About Me](https://github.com/pyoncord/Bunny) says
> A mod for Discord's mobile apps, a fork of [Vendetta](https://github.com/vendetta-mod/Vendetta/).

To provide more clarity, I will add a note that says it is specifically designed for non-rooted devices, unlike BunnyXpose, which is intended for rooted devices.

2024-07-25 16:58 UTC, Jalenzzz commented on README.md
> +* [@Xinto](https://github.com/X1nto/) - For the preference manager.
Gotcha!

2024-07-25 16:59 UTC, Jalenzzz commented on README.md
> +###### This application is not affiliated with or endorsed by Discord Inc. Use of modified versions of the Discord app may violate Discord’s terms of service. Use at your own risk.
Got it!

2024-07-25 17:04 UTC, Jalenzzz commented
There we go :)

2024-09-11 04:32 UTC, closed without merging